# Generated by Django 2.2 on 2019-04-28 17:41

from django.db import migrations, models
import django.db.models.deletion
import player_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('savefile', models.FileField(blank=True, null=True, upload_to=player_module.models.SavefileUpload('player'))),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.School')),
            ],
        ),
    ]
