# Generated by Django 2.2 on 2019-04-28 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='Picture/Question')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question')),
            ],
        ),
    ]
