# Generated by Django 2.2 on 2019-04-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0002_questionpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionpicture',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subjectId',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typeId',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_module.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuestionType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionpicture',
            name='file',
            field=models.ImageField(upload_to='picture/question'),
        ),
    ]
