# Generated by Django 2.2 on 2019-04-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0003_auto_20190429_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='for_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
