# Generated by Django 2.2 on 2019-05-04 12:49

from django.db import migrations, models
import django.utils.timezone
import question_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0004_auto_20190429_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionpicture',
            name='file',
            field=models.ImageField(upload_to=question_module.models.PictureUpload('question/pictures')),
        ),
    ]
